# Generated by Django 2.2.6 on 2019-10-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_auto_20190521_2124'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='value',
            name='engine_valu_mooclet_c50aaf_idx',
        ),
        migrations.RemoveIndex(
            model_name='value',
            name='engine_valu_mooclet_78bea6_idx',
        ),
        migrations.RemoveIndex(
            model_name='value',
            name='engine_valu_learner_00f366_idx',
        ),
        migrations.RemoveIndex(
            model_name='value',
            name='engine_valu_learner_0ec754_idx',
        ),
        migrations.AlterField(
            model_name='policyparameters',
            name='mooclet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Mooclet'),
        ),
        migrations.AlterField(
            model_name='policyparameters',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Policy'),
        ),
        migrations.AlterField(
            model_name='policyparametershistory',
            name='mooclet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Mooclet'),
        ),
        migrations.AlterField(
            model_name='policyparametershistory',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Policy'),
        ),
        migrations.AlterField(
            model_name='value',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Variable'),
        ),
        migrations.AlterField(
            model_name='version',
            name='mooclet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Mooclet'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet', 'learner', 'version'], name='value_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['mooclet'], name='value_mooclet_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['learner'], name='value_learner_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['learner', 'timestamp'], name='value_timestamp_idx'),
        ),
    ]
