# Generated by Django 2.2.6 on 2022-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0024_auto_20191011_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='max_value',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='variable',
            name='min_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='variable',
            name='sample_thres',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='variable',
            name='value_type',
            field=models.CharField(choices=[('BIN', 'binary'), ('ORD', 'ordinary'), ('CONT', 'continuous')], default='BIN', max_length=100),
        ),
    ]
