# Generated by Django 2.2.6 on 2019-10-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_exchange', '0008_qualtricsontaskdataexchange_mooclets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualtricsontaskdataexchange',
            name='data_input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_exchange.QualtricsSurvey'),
        ),
        migrations.AlterField(
            model_name='qualtricsontaskdataexchange',
            name='data_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_exchange.OnTaskWorkflow'),
        ),
    ]
